# Generated by Django 4.1.3 on 2023-01-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cart',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
