# Generated by Django 4.1.3 on 2023-01-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_order_onion_order_sweet_alter_order_total_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cart',
        ),
    ]
