# Generated by Django 4.1.3 on 2023-01-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_order_total_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cart',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
