# Generated by Django 4.1.3 on 2023-01-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_total_cart_order_total_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_bill',
            field=models.CharField(max_length=150),
        ),
    ]
