# Generated by Django 4.1.3 on 2023-01-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_order_total_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='desc',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='onion',
            new_name='Onion_pizza',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='sweet',
            new_name='Sweet_Corn_pizza',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_bill',
            field=models.TextField(),
        ),
    ]
